name: kadhai_kuzhandhai
description: Tamil AI storytelling app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.7.0
  speech_to_text: ^6.3.0
  provider: ^6.1.1
  rive: ^0.11.17
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/stories/
    - assets/images/